Repository dnd-side-project/dnd-7th-4-frontend, pull requests merged in 2022-08, with the labels that each got.

#36 Featrue/18/screenonly
  src/styles/GlobalStyle.js
Labels: Type: Feature

#54 Feature/31/home
  package-lock.json
  package.json
  src/components/Header/Header.style.js
  src/components/WeatherForecast/Days/Days.jsx
  src/components/WeatherForecast/ThisWeek/ThisWeek.jsx
  src/components/WeatherForecast/ThisWeek/ThisWeek.style.js
Labels: Priority: Critical, Status: In Progress, Type: Feature

#57 Feature/43/location
  README.md
  src/Auth.js
  src/api/api.js
  src/assets/icon/delete.svg
  src/assets/icon/kakao-login.png
  src/components/Kakao/Kakao.jsx
  src/components/Kakao/Kakao.style.js
  src/components/Kakao/index.js
  src/components/KakaoLogin/KakaoLogin.jsx
  src/components/KakaoLogin/KakaoLoginAuth/KakaoLoginAuth.jsx
  src/components/KakaoLogin/KakaoLoginAuth/index.js
  src/components/KakaoLogin/KakaoLoginBtn/KakaoLoginBtn.jsx
  src/components/KakaoLogin/KakaoLoginBtn/KakaoLoginBtn.style.js
  src/components/KakaoLogin/KakaoLoginBtn/index.js
  src/components/KakaoLogin/index.js
  src/components/Location/Location.style.js
  src/components/Location/LocationResult/LocationResult.jsx
  src/components/Location/LocationResult/LocationResult.style.js
  src/components/Location/LocationResult/index.js
  src/components/Location/LocationSearch/LocationSearch.jsx
  src/components/Location/LocationSearch/LocationSearch.style.js
  src/components/Location/LocationSearch/index.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.js
  src/pages/LoginPage/index.js
  src/routes/Router.jsx
Labels: Priority: Critical, Status: In Progress, Type: Feature

#58 Feature/31/home
  src/assets/images/cloudy.svg
  src/assets/images/cloudySubtractBack.svg
  src/assets/images/cloudySubtractFront.svg
  src/assets/images/heavyRain.svg
  src/assets/images/rainy.svg
  src/assets/images/sunny.svg
  src/assets/images/sunnySubtractBack.svg
  src/assets/images/sunnySubtractFront.svg
  src/assets/images/veryCloudy.svg
  src/assets/images/wet.svg
  src/components/MoreWeatherInfo/MoreWeatherInfo.jsx
  src/components/MoreWeatherInfo/MoreWeatherInfo.style.js
  src/components/WeatherForecast/Days/Days.jsx
  src/components/WeatherForecast/Days/Days.style.js
  src/components/WeatherForecast/ThisWeek/ThisWeek.jsx
  src/components/WeatherForecast/ThisWeek/ThisWeek.style.js
  src/components/WeatherForecast/WeatherForecast.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Home.style.js
  src/recoil/weather/index.js
  src/recoil/weather/withSelectSky.js
  src/styles/DefaultTheme.js
Labels: Priority: Critical, Status: In Progress, Type: Feature

#61 Feature/48/slidemenu
  src/assets/icon/arrow-gray.svg
  src/components/SlideMenu/SlideMenu.jsx
  src/components/SlideMenu/SlideMenu.style.js
Labels: Priority: High, Status: In Progress, Type: Feature

#74 Feature/70/homeanimation
  public/favicon.ico
  public/index.html
  src/components/WeatherForecast/Days/Days.jsx
  src/components/WeatherForecast/Days/Days.style.js
  src/pages/Home/Home.style.js
  src/styles/DefaultTheme.js
Labels: Priority: Critical, Status: In Progress

#81 Refactor/80/home
  src/assets/images/cloudyGround.svg
  src/assets/images/cloudyGroundBack.svg
  src/assets/images/cloudySubtractBack.svg
  src/assets/images/cloudySubtractFront.svg
  src/assets/images/sunnyGround.svg
  src/assets/images/sunnyGroundBack.svg
  src/assets/images/sunnySubtractBack.svg
  src/assets/images/sunnySubtractFront.svg
  src/components/Footer/Footer.style.js
  src/components/MoreWeatherInfo/MoreWeatherInfo.style.js
  src/components/UpdateTIme/UpdateTime.style.js
  src/components/WeatherForecast/Days/Days.jsx
  src/components/WeatherForecast/Days/Days.style.js
  src/components/WeatherForecast/ThisWeek/ThisWeek.jsx
  src/components/WeatherForecast/ThisWeek/ThisWeek.style.js
  src/pages/Home/Home.style.js
  src/styles/DefaultTheme.js
Labels: Priority: High, Status: Reviewing, Status: In Progress
